### ISSUE TITLE
Solution/retry buttons for H5P won't disable

### ISSUE THREAD

**Issue by licethrey91** [h5p/h5p-question-set#116]
Hi Team, 

When using Content Bank with H5p, the "show solution" and "retry" buttons for "Question still appear even after being disabled. 

Steps to replicate:
1. As an admin, navigate to a course or create a new one. 
2. Go to Content Bank
3. Click Add>"question set"
4. Fill in the minimum requirements (create at least one question, does not matter if multiple choice, true/false)
5. Click on behavioural settings and uncheck enable "retry" button and enable "show solution" button
6. Click on Settings for "check", "show solution" and "retry" and make both buttons "disabled" and save.
7. Now go to Content Bank and click on your newly created question set. 
8. Click an answer and finish, the "show solution" and "retry" buttons still show. 
9. Go back to the course and add the H5P activity (not the interactive content) choose the activity you just created and save it. 
10. Login as a student and navigate to H5P, click answers and finish, you will notice the buttons still show for a student. 

Any combination of the settings still result in the same behavior of the buttons still displaying. 

This is across all themes. This was tested on Moodle testing site
<img width="955" alt="Screenshot 2022-12-21 at 9 26 18 AM" src="https://user-images.githubusercontent.com/81388522/208928134-705937c6-4340-4d12-a55a-fe470343d04e.png">

Thanks.

**Comment by otacke** [comment]
@licethrey91 There's no bug here.

You are disabling the `retry` and `show solution` buttons for the exercises within the quiz, but not for the quiz itself. The quiz has separate settings for the end screen above the `Settings for "Check", "Show solution" and "Retry"` that you mention in your description.

**Comment by licethrey91** [comment]
Hi @otacke, 
Thanks for your help, I have made the configuration for the "Retry" button you mentioned, however it is not being applied.

<img width="917" alt="Screenshot 2022-12-21 at 11 08 30 AM" src="https://user-images.githubusercontent.
<img width="564" alt="Screenshot 2022-12-21 at 11 08 46 AM" src="https://user-images.githubusercontent.com/81388522/208950445-63b08384-2a3c-4d32-af29-c5be44aaa7da.png">
com/81388522/208950417-70b9ac4a-4e3a-4c4e-9be2-c2b386e14eda.png">

**Comment by otacke** [comment]
@licethrey91 As I said, you're not changing the settings for the end screen. These are the droids that you are looking for ...

![Screenshot_20221221_220538_Brave-picsay](https://user-images.githubusercontent.com/16688047/209003364-59442214-12fa-4b12-8475-699ec48f44da.jpg)

**Comment by licethrey91** [comment]
Hi @otacke,
Thank you very much for your help, I made this configuration that you share and it works. ☺️
